receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317

exporters:
  debug:
    verbosity: detailed

  otlp:
    endpoint: jaeger-all-in-one:4317
    tls:
      insecure: true

  otlphttp:
    endpoint: "http://loki:3100"

  prometheus:
    endpoint: ":9201" 
    send_timestamps: true
    metric_expiration: 180m
    enable_open_metrics: true

processors:
  batch:

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp, debug]
      processors: [batch]

    logs:
      receivers: [otlp]
      exporters: [otlphttp, debug]
      processors: [batch]

    metrics:
      receivers: [otlp]
      exporters: [prometheus, debug]
      processors: [batch]
  telemetry:
    metrics:
      readers:
        - pull:
            exporter:
              prometheus:
                host: '0.0.0.0'
                port: 8888